import { Data } from "./types";

//columns for table
export const columns = [
  { id: "nombre", label: "Nombre" },
  { id: "email", label: "Correo Electrónico" },
  { id: "phoneNumber", label: "Número de telefono" },
  { id: "role", label: "Rol" },
  { id: "status", label: "Estatus" },
  { id: "actions", label: "Acciones" },
];

//array generated with 50 users aleatory
export const initialUsers: Data[] = [
  {
    nombre: "Juan Pérez",
    correo: "juan.perez@example.com",
    telefono: "654789012",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "María Gómez",
    correo: "maria.gomez@example.com",
    telefono: "623456789",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Carlos Rodríguez",
    correo: "carlos.rodriguez@example.com",
    telefono: "612345678",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Laura Sánchez",
    correo: "laura.sanchez@example.com",
    telefono: "672345678",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Luis Martínez",
    correo: "luis.martinez@example.com",
    telefono: "665432109",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Ana López",
    correo: "ana.lopez@example.com",
    telefono: "698765432",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Pedro Díaz",
    correo: "pedro.diaz@example.com",
    telefono: "661234567",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Isabel Fernández",
    correo: "isabel.fernandez@example.com",
    telefono: "670987654",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "David González",
    correo: "david.gonzalez@example.com",
    telefono: "659876543",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Carmen Ruiz",
    correo: "carmen.ruiz@example.com",
    telefono: "678654321",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "José Hernández",
    correo: "jose.hernandez@example.com",
    telefono: "669876543",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Eva Martínez",
    correo: "eva.martinez@example.com",
    telefono: "650123456",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Rafael Pérez",
    correo: "rafael.perez@example.com",
    telefono: "688765432",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Lucía Sánchez",
    correo: "lucia.sanchez@example.com",
    telefono: "623489576",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Fernando Díaz",
    correo: "fernando.diaz@example.com",
    telefono: "699876543",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Sofía Ruiz",
    correo: "sofia.ruiz@example.com",
    telefono: "612398476",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Marcos López",
    correo: "marcos.lopez@example.com",
    telefono: "677123456",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Victoria Fernández",
    correo: "victoria.fernandez@example.com",
    telefono: "633456789",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Antonio García",
    correo: "antonio.garcia@example.com",
    telefono: "698765430",
    rol: "admin",
    estado: "Inactivo",
  },
  {
    nombre: "Patricia Ramírez",
    correo: "patricia.ramirez@example.com",
    telefono: "665432176",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "José María Pérez",
    correo: "josemaria.perez@example.com",
    telefono: "654321234",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Beatriz Gómez",
    correo: "beatriz.gomez@example.com",
    telefono: "612334567",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Juan Carlos Martínez",
    correo: "juancarlos.martinez@example.com",
    telefono: "669876432",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Cristina Rodríguez",
    correo: "cristina.rodriguez@example.com",
    telefono: "623487654",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Álvaro Sánchez",
    correo: "alvaro.sanchez@example.com",
    telefono: "634765432",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Ricardo López",
    correo: "ricardo.lopez@example.com",
    telefono: "609876543",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Ana Ramírez",
    correo: "ana.ramirez@example.com",
    telefono: "650987654",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Manuel Hernández",
    correo: "manuel.hernandez@example.com",
    telefono: "665432111",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Raquel García",
    correo: "raquel.garcia@example.com",
    telefono: "678654789",
    rol: "admin",
    estado: "Inactivo",
  },
  {
    nombre: "Javier Fernández",
    correo: "javier.fernandez@example.com",
    telefono: "690123456",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Laura Pérez",
    correo: "laura.perez@example.com",
    telefono: "667890123",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Tomás Sánchez",
    correo: "tomas.sanchez@example.com",
    telefono: "623456832",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Pablo Martínez",
    correo: "pablo.martinez@example.com",
    telefono: "654789765",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Isabel Díaz",
    correo: "isabel.diaz@example.com",
    telefono: "699234567",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Elena Rodríguez",
    correo: "elena.rodriguez@example.com",
    telefono: "612345678",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Carlos Ruiz",
    correo: "carlos.ruiz@example.com",
    telefono: "677890123",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Mónica Sánchez",
    correo: "monica.sanchez@example.com",
    telefono: "690345678",
    rol: "admin",
    estado: "Inactivo",
  },
  {
    nombre: "Juan Gómez",
    correo: "juan.gomez@example.com",
    telefono: "669876532",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Sara Pérez",
    correo: "sara.perez@example.com",
    telefono: "654789321",
    rol: "admin",
    estado: "Inactivo",
  },
  {
    nombre: "Marta González",
    correo: "marta.gonzalez@example.com",
    telefono: "623456789",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Antonio Ruiz",
    correo: "antonio.ruiz@example.com",
    telefono: "650234567",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Laura Díaz",
    correo: "laura.diaz@example.com",
    telefono: "654123456",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Ricardo Martínez",
    correo: "ricardo.martinez@example.com",
    telefono: "698765432",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Cristina López",
    correo: "cristina.lopez@example.com",
    telefono: "678765432",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Miguel Fernández",
    correo: "miguel.fernandez@example.com",
    telefono: "654321765",
    rol: "admin",
    estado: "Inactivo",
  },
  {
    nombre: "Patricia Ramírez",
    correo: "patricia.ramirez@example.com",
    telefono: "612345678",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Alfredo Pérez",
    correo: "alfredo.perez@example.com",
    telefono: "634567890",
    rol: "usuario",
    estado: "Inactivo",
  },
  {
    nombre: "Susana López",
    correo: "susana.lopez@example.com",
    telefono: "612234567",
    rol: "admin",
    estado: "Activo",
  },
  {
    nombre: "Eduardo García",
    correo: "eduardo.garcia@example.com",
    telefono: "677345678",
    rol: "usuario",
    estado: "Activo",
  },
  {
    nombre: "Raúl Sánchez",
    correo: "raul.sanchez@example.com",
    telefono: "690123456",
    rol: "admin",
    estado: "Inactivo",
  },
];
